common: &common
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: que_me_pongo_2
  password: que_me_pongo_2

test:
  <<: *common
  database: que_me_pongo_2_test
  pool: 5
  timeout: 5000

development:
  <<: *common
  database: que_me_pongo_2_development
  pool: 5
  timeout: 5000
